# Comparing Operators

In [2]:
import numpy as np
import pandas as pd

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
a2 = np.array([[1,2,3.3],[4,5,6.5]])
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [7]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [8]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [9]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [10]:
a1 > 5

array([False, False, False])

In [11]:
a1 < 5

array([ True,  True,  True])

In [12]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

In [13]:
a1 == a1

array([ True,  True,  True])

## Sorting arrays 

In [15]:
random_array = np.random.randint(10,size= (3,5))
random_array

array([[8, 1, 9, 3, 3],
       [2, 0, 6, 4, 3],
       [2, 9, 1, 4, 5]])

In [16]:
random_array.shape

(3, 5)

In [17]:
np.sort(random_array)

array([[1, 3, 3, 8, 9],
       [0, 2, 3, 4, 6],
       [1, 2, 4, 5, 9]])

In [18]:
np.argsort(random_array) # it return indices of the elements in sorting way

array([[1, 3, 4, 0, 2],
       [1, 0, 4, 3, 2],
       [2, 0, 3, 4, 1]], dtype=int64)

In [19]:
a1

array([1, 2, 3])

In [20]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [21]:
np.argmax(a1)

2

In [22]:
random_array

array([[8, 1, 9, 3, 3],
       [2, 0, 6, 4, 3],
       [2, 9, 1, 4, 5]])

In [23]:
np.argmax(random_array)

2

In [24]:
np.argmax(random_array,axis=0)

array([0, 2, 0, 1, 2], dtype=int64)

In [48]:
np.argmax(random_array, axis =1)

array([2, 2, 1], dtype=int64)

## 6. Practical Example of NUMPY

<img src ="panda.png"/>

In [83]:
# Turn an image into a Numpy array
from matplotlib.image import imread

In [89]:
panda = imread("panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [91]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [93]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [95]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="car-photo.png"/>

In [102]:
car = imread("car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


In [104]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

<img src = "dog-photo.png"/>

In [112]:
dog = imread("dog-photo.png")
print(type(dog))

<class 'numpy.ndarray'>


In [114]:
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32)