## CLASSIFICATION MODEL  

In [7]:
import pandas as pd


In [8]:
df = pd.read_csv("heart-disease.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [9]:
len(df)

303

TRYING LINEAR SVC

In [11]:
from sklearn.svm import LinearSVC
import numpy as np
from sklearn.model_selection import train_test_split
#setup random seed
np.random.seed(42)

#make the data
X= df.drop("target",axis=1)
y= df["target"]

#split the data
X_train , X_test , y_train ,y_test = train_test_split(X,y, test_size=0.2)

#Instantiate LinearSVC
clf= LinearSVC()
clf.fit(X_train,y_train)

#Evaluate the LinearSVC
clf.score(X_test, y_test)

0.8688524590163934

In [12]:
df["target"].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [13]:
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.model_selection import train_test_split
#setup random seed
np.random.seed(42)

#make the data
X= df.drop("target",axis=1)
y= df["target"]

#split the data
X_train , X_test , y_train ,y_test = train_test_split(X,y, test_size=0.2)

#Instantiate rfc
clf= RandomForestClassifier()
clf.fit(X_train,y_train)

#Evaluate the rfc
clf.score(X_test, y_test)

0.8524590163934426

In [14]:
df



age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

# Fit the model on our data and use it to make predictions

In [16]:
from sklearn.ensemble import RandomForestClassifier
np.random.seed(42)

X= df.drop("target",axis =1)
y= df["target"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.2)

clf = RandomForestClassifier()

clf.fit(X_train,y_train)
clf.score(X_test,y_test) #accuracy score

0.8524590163934426

In [17]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [18]:
y.head()


0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

# making predictions in machine learning model 

use a trained model to make predictions 

In [21]:
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [22]:
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

# Compare predictions to truth labels to evaluate the model 

In [24]:
y_preds= clf.predict(X_test)

In [25]:
np.mean(y_preds == y_test)

0.8524590163934426

In [26]:
clf.score(X_test, y_test)

0.8524590163934426

In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.8524590163934426

# making predictions with predict_proba() 

# predict_proba() return probabilities of a classification model 

In [30]:
clf.predict_proba(X_test[:6])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82],
       [0.14, 0.86]])

In [31]:
# trying predict() on the same data

In [32]:
clf.predict(X_test[:6])

array([0, 1, 1, 0, 1, 1], dtype=int64)

In [33]:
df["target"].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [34]:
housing = pd.read_csv("housing.csv")
housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [35]:
#housing_df = pd.DataFrame(housing["data"], columns= housing["feature_names"])
#housing_df

In [36]:
#housing_df["MadHouseVal"] = housing["target"]

In [37]:
#housing_df.head()
#housing_df["Target"] = housing["target"]
#housing_df

In [38]:
housing_df = housing


In [39]:
housing_df.rename(columns={"median_house_value": "Target"}, inplace=True)
housing_df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income    Target ocean_proximity  
0           322.0       126.0         8.3252  452600.0        NEAR BAY  
1          2401.0      1138.0         8.3014  358500.0        NEAR BAY  
2           496.0       177.0         7.2574  352100.0        NEAR BAY  
3           558.0       219.0         5.6431  341300.0        NEAR BAY  
4           565.0       259.0         3.8462  342200.0        NEAR BAY  
...           ...         ...            ...       ...             ...  
20635       845.0       330.0         1.5603   78100.0          INLAND  
20636       356.0       114.0         2.5568   77100.0          INLAND  
20637      1007.0       433.0         1.7000   92300.0          INLAND  
20638       741.0       349.0         1.8672   84700.0          INLAND  
20639      1387.0       530.0         2.3886   89400.0          INLAND  

[20640 rows x 10 columns]

In [40]:
#housing_df = housing_df.drop("MadHouseVal", axis=1)

In [41]:
housing_df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income    Target ocean_proximity  
0           322.0       126.0         8.3252  452600.0        NEAR BAY  
1          2401.0      1138.0         8.3014  358500.0        NEAR BAY  
2           496.0       177.0         7.2574  352100.0        NEAR BAY  
3           558.0       219.0         5.6431  341300.0        NEAR BAY  
4           565.0       259.0         3.8462  342200.0        NEAR BAY  
...           ...         ...            ...       ...             ...  
20635       845.0       330.0         1.5603   78100.0          INLAND  
20636       356.0       114.0         2.5568   77100.0          INLAND  
20637      1007.0       433.0         1.7000   92300.0          INLAND  
20638       741.0       349.0         1.8672   84700.0          INLAND  
20639      1387.0       530.0         2.3886   89400.0          INLAND  

[20640 rows x 10 columns]

In [42]:
from sklearn.ensemble import RandomForestRegressor
np.random.seed(22)

X = housing_df.drop("Target",axis=1)
y = housing_df["Target"]

X = pd.get_dummies(X, columns=["ocean_proximity"])

X_train , X_test ,y_train , y_test = train_test_split(X,y,test_size = 0.2)

model = RandomForestRegressor()

model.fit(X_train , y_train)

y_preds = model.predict(X_test)

In [43]:
y_preds[:10]

array([122791., 240785.,  59628., 197609., 123054., 101084., 264713.,
       103403., 246215., 216538.])

In [44]:
np.array(y_test[:10])

array([140200., 225000.,  61300., 117400., 119500.,  79200., 311800.,
       104200., 241100., 248600.])

In [45]:
len(y_test)

4128

In [46]:
len(y_preds)

4128