# Comparing Operators

In [2]:
import numpy as np
import pandas as pd

In [4]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [6]:
a2 = np.array([[1,2,3.3],[4,5,6.5]])
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [12]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [14]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [18]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [22]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [24]:
a1 > 5

array([False, False, False])

In [26]:
a1 < 5

array([ True,  True,  True])

In [28]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

In [30]:
a1 == a1

array([ True,  True,  True])